all:build/kerneldisplay.o build/graphics.o
build/kerneldisplay.o:
	gcc ${CFLAGS} -c kerneldisplay.c -o ${BASE_DIR}/build/kerneldisplay.o
build/graphics.o:
	gcc ${CFLAGS} -c graphics.c -o ${BASE_DIR}/build/graphics.o